### ISSUE TITLE
Crash on version 1.11

### ISSUE THREAD

**Issue by VENT0** [InventivetalentDev/CompactNPCLib#31]
## What steps will reproduce the problem?  
1. Server loading

## What Spigot version are you using? *Type /version* 
Spigot 1.11

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  (SORRY. I AM NOT REGISTERED ON PASTEBIN)
`[14:36:00] [Server thread/ERROR]: java.lang.RuntimeException: java.lang.NullPointerException initializing NPCLib v2.2.6 (Is it up to date?)
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at org.inventivetalent.npclib.registry.NPCRegistry.getOrGenerateClass(NPCRegistry.java:92) ~[?:?]
	at org.inventivetalent.npclib.registry.NPCRegistry.injectClasses(NPCRegistry.java:75) ~[?:?]
	at org.inventivetalent.npclib.NPCLib.load(NPCLib.java:87) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:102) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.registerAPI(APIManager.java:122) ~[?:?]
	at org.inventivetalent.npclib.NPCLibPlugin.onLoad(NPCLibPlugin.java:21) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at org.inventivetalent.npclib.reflection.resolver.wrapper.FieldWrapper.get(FieldWrapper.java:54) ~[?:?]
	at org.inventivetalent.npclib.registry.NPCRegistry.injectEntity(NPCRegistry.java:100) ~[?:?]
	at org.inventivetalent.npclib.registry.NPCRegistry.getOrGenerateClass(NPCRegistry.java:88) ~[?:?]
	... 9 more
Caused by: java.lang.NullPointerException
	at org.inventivetalent.npclib.reflection.resolver.wrapper.FieldWrapper.get(FieldWrapper.java:52) ~[?:?]
	at org.inventivetalent.npclib.registry.NPCRegistry.injectEntity(NPCRegistry.java:100) ~[?:?]
	at org.inventivetalent.npclib.registry.NPCRegistry.getOrGenerateClass(NPCRegistry.java:88) ~[?:?]
	... 9 more`

`[14:36:01] [Server thread/INFO]: [NPCLib] Enabling NPCLib v2.2.6
[14:36:01] [Server thread/ERROR]: Error occurred while enabling NPCLib v2.2.6 (Is it up to date?)
org.inventivetalent.apihelper.exception.MissingHostException: API 'org.inventivetalent.npclib.NPCLib' is disabled, but no other Hosts have been registered
	at org.inventivetalent.apihelper.RegisteredAPI.getNextHost(RegisteredAPI.java:63) ~[?:?]
	at org.inventivetalent.apihelper.RegisteredAPI.init(RegisteredAPI.java:83) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:155) ~[?:?]
	at org.inventivetalent.apihelper.APIManager.initAPI(APIManager.java:188) ~[?:?]
	at org.inventivetalent.npclib.NPCLibPlugin.onEnable(NPCLibPlugin.java:31) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-f950f8e-c6d6844]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]`

**Comment by lizardfreak321** [comment]
v2.2.6 doesn't support 1.11, use the newest dev build here: http://ci.inventivetalent.org/job/CompactNPCLib/

Keep in mind it is not fully stable. https://github.com/InventivetalentDev/CompactNPCLib/issues/30

**Comment by RobinMCNetwork** [comment]
Just a heads up, you don't need to be registered on pastebin to use the service. If you are looking for a pasting service without ads, use http://paste.md-5.net/ :)

**Comment by VENT0** [comment]
Thanks. Solved.
