### ISSUE TITLE
IronGolem crash

### ISSUE THREAD

**Issue by InventivetalentDev** [InventivetalentDev/CompactNPCLib#5]
Server crashes when IronGolem NPC takes damage.  
Apparently caused by the `damageArmor(float)` method, which doesn't actually have a @Watch annotation.

https://paste.inventivetalent.org/osokirunuy.log
```
[00:04:13 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Ticking entity
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:815) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.RuntimeException: Failed to invoke @Watch method void damageArmor(float) with args: [3.0, SuperSwitch(state=PASS)]
        at org.inventivetalent.npclib.watcher.AnnotatedMethodWatcher.methodCalled(AnnotatedMethodWatcher.java:104) ~[?:?]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.methodCalled(NPCEntityIronGolem.java) ~[?:?]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageArmor(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1253) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageEntity0(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageEntity(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityMonster.B(EntityMonster.java:72) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.B(EntityZombie.java:237) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalMeleeAttack.a(SourceFile:125) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalMeleeAttack.e(SourceFile:117) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalZombieAttack.e(SourceFile:28) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalSelector.a(SourceFile:129) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.doTick(EntityInsentient.java:667) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityLiving.n(EntityLiving.java:1961) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.n(EntityInsentient.java:512) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityMonster.n(EntityMonster.java:28) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.n(EntityZombie.java:176) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1817) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:240) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityMonster.m(EntityMonster.java:32) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.m(EntityZombie.java:233) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1621) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.g(World.java:1596) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        ... 4 more
Caused by: java.lang.IllegalArgumentException
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.inventivetalent.npclib.watcher.AnnotatedMethodWatcher.methodCalled(AnnotatedMethodWatcher.java:102) ~[?:?]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.methodCalled(NPCEntityIronGolem.java) ~[?:?]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageArmor(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1253) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageEntity0(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageEntity(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityMonster.B(EntityMonster.java:72) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.B(EntityZombie.java:237) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalMeleeAttack.a(SourceFile:125) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalMeleeAttack.e(SourceFile:117) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalZombieAttack.e(SourceFile:28) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalSelector.a(SourceFile:129) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.doTick(EntityInsentient.java:667) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityLiving.n(EntityLiving.java:1961) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.n(EntityInsentient.java:512) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityMonster.n(EntityMonster.java:28) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.n(EntityZombie.java:176) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1817) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:240) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityMonster.m(EntityMonster.java:32) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.m(EntityZombie.java:233) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1621) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.g(World.java:1596) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        ... 4 more
[00:04:13 ERROR]:       Cause of unexpected exception was
java.lang.RuntimeException: Failed to invoke @Watch method void damageArmor(float) with args: [3.0, SuperSwitch(state=PASS)]
        at org.inventivetalent.npclib.watcher.AnnotatedMethodWatcher.methodCalled(AnnotatedMethodWatcher.java:104) ~[?:?]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.methodCalled(NPCEntityIronGolem.java) ~[?:?]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageArmor(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity0(EntityLiving.java:1253) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageEntity0(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityLiving.damageEntity(EntityLiving.java:834) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at org.inventivetalent.npclib.generated.entity.NPCEntityIronGolem.damageEntity(NPCEntityIronGolem.java) ~[?:?]
        at net.minecraft.server.v1_10_R1.EntityMonster.B(EntityMonster.java:72) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.B(EntityZombie.java:237) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalMeleeAttack.a(SourceFile:125) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalMeleeAttack.e(SourceFile:117) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalZombieAttack.e(SourceFile:28) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.PathfinderGoalSelector.a(SourceFile:129) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.doTick(EntityInsentient.java:667) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityLiving.n(EntityLiving.java:1961) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.n(EntityInsentient.java:512) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityMonster.n(EntityMonster.java:28) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.n(EntityZombie.java:176) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityLiving.m(EntityLiving.java:1817) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityInsentient.m(EntityInsentient.java:240) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityMonster.m(EntityMonster.java:32) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.EntityZombie.m(EntityZombie.java:233) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.entityJoinedWorld(World.java:1621) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.g(World.java:1596) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.World.tickEntities(World.java:1430) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.WorldServer.tickEntities(WorldServer.java:632) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:804) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-6016ac7-10c10b3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.IllegalArgumentException
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
        at org.inventivetalent.npclib.watcher.AnnotatedMethodWatcher.methodCalled(AnnotatedMethodWatcher.java:102) ~[?:?]
        ... 30 more
```

**Comment by InventivetalentDev** [comment]
Was caused by method signatures matching the wrong methods (https://github.com/InventivetalentDev/ReflectionHelper/commit/0c7fb62ca4afcb62d8c57dd0c9d7b2773c10330a)
